# Generated by Django 3.2.6 on 2021-10-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
