# Generated by Django 3.2.6 on 2021-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_auto_20211009_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.PositiveBigIntegerField(),
        ),
    ]
